### ISSUE TITLE
create red pitaya hardware module

### ISSUE THREAD

**Issue by mvbnano** [QMAPP-mq/qudi#37]
A Red Pitaya hardware module will be useful for many things. Our immediate applications will be to control the galvo mirrors and to trigger the SMIQ ODMR sequence.

**Comment by mvbnano** [comment]
Looks like by using a combination of the [```RPyC```](https://pypi.python.org/pypi/rpyc/) (Remote Python Call) and [```PyRedPitaya```](https://pypi.python.org/pypi/PyRedPitaya/1.0) packages you can connect to RP boards from the terminal

```python
from rpyc import connect
from PyRedPitaya.pc import RedPitaya

conn = connect(REDPITAYA_IP, port=18861)
redpitaya = RedPitaya(conn)

print redpitaya.ams.temp # Read property
redpitaya.hk.led = 0b10101010 # Write property

from time import sleep
from pylab import *

redpitaya.scope.setup(frequency = 100, trigger_source=1)
sleep(100E-3)
plot(redpitaya.scope.times, redpitaya.scope.data_ch1)
show()
```

**Comment by mvbnano** [comment]
Upon completion of remote connecting test and satisfies oscilloscope requirements for @CyLap , then purchase 3x Red Pitayas.

Can be easily purchased through RS Components.

**Comment by latchr** [comment]
Today we had a chat about the convergence of this task with the similar one for using the TimeTagger for ODMR. It is important to think of the Red Pitaya module separately from the counting (which will be done using the TimeTagger).

The code that is needed here is:
1. Hardware module to drive the Red Pitaya as a "general scanner"
2. Interface defined for general scanner.
3. Interface defined for hardware trigger.
4. In the Red Pitaya hw module we need to import the hardware trigger interface and pass it through to the RP class.  This will look like the opening lines of the NI X-series hw module.
5. There will need to be a separate "triggered counter" interface and HW module created (#43)
6. We will need an interfuse which connects the "general scanner" (RP), "hardware trigger" (RP), "triggered counter" (TT) into a "confocal scanner". In particular this will revolve around the scan_line method.

The final config will look a bit like this

```
hardware:
    rp_scanner:
        module.Class: 'red_pitaya.RedPitaya'
        ...V output channels...
        trigger_channel: 'D0'

    mytimetagger:
        module.Class: 'timetagger.TimeTagger'
        
logic:

    rp_tt_interfuse:
        module.Class: 'interfuse.scanner_trigger_counter_interfuse.ScannerTriggerCounterInterfuse'
        connect:
            scanner: 'rp_scanner'
            trigger: 'mytimetagger'
            counter: 'mytimetagger'

    scannerlogic:
        module.Class: 'confocal_logic.ConfocalLogic'
        connect:
            confocalscanner1: 'rp_tt_interfuse'
            savelogic: 'savelogic'
```
